"""Local medical-procedure cache and embedding-model adapter."""

import pickle
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer


class MedicalDatabase:
    def __init__(self, config):
        """Initialize database with configuration"""
        self.config = config
        self.procedures = []
        self.embeddings = None
        self.embedding_model = None

    def load(self, cache_dir):
        """Load the trusted, locally generated procedure and embedding cache."""
        cache_path = Path(cache_dir)
        procedures_path = cache_path / "procedures.pkl"
        embeddings_path = cache_path / "embeddings.npy"
        if not procedures_path.is_file() or not embeddings_path.is_file():
            raise FileNotFoundError(
                f"Retrieval cache is incomplete at {cache_path}. "
                "Run `uv run python scripts/build_database.py`."
            )

        # Load procedures. Cache file is generated by our own build_database.py
        # and stored under the project's data/ dir — source is trusted.
        with procedures_path.open("rb") as f:
            self.procedures = pickle.load(f)  # noqa: S301 — trusted local cache

        # Load embeddings
        with embeddings_path.open("rb") as f:
            self.embeddings = np.load(f)

        # Load embedding model
        model_name = self.config["database"]["embedding_model"]
        self.embedding_model = SentenceTransformer(model_name)
