"""
Medical Procedures Database
Handles loading and storing medical procedure data with embeddings
"""

import pickle
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer


class MedicalDatabase:
    def __init__(self, config):
        """Initialize database with configuration"""
        self.config = config
        self.procedures = []
        self.embeddings = None
        self.embedding_model = None

    def load(self, cache_dir):
        """Load database from cache directory"""
        cache_path = Path(cache_dir)

        # Load procedures. Cache file is generated by our own build_database.py
        # and stored under the project's data/ dir — source is trusted.
        with open(cache_path / "procedures.pkl", "rb") as f:
            self.procedures = pickle.load(f)  # noqa: S301 — trusted local cache

        # Load embeddings
        with open(cache_path / "embeddings.npy", "rb") as f:
            self.embeddings = np.load(f)

        # Load embedding model
        model_name = self.config["database"]["embedding_model"]
        self.embedding_model = SentenceTransformer(model_name)
